cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
project(cpp)

add_subdirectory(calibration_from_file)
add_subdirectory(code_reader_from_file)
add_subdirectory(get_first_pixel)
add_subdirectory(getting_started_with_camera)
add_subdirectory(hdr)
add_subdirectory(hdr_from_file)
add_subdirectory(image_region_from_file)
add_subdirectory(morphology)
add_subdirectory(nion_point_cloud)
add_subdirectory(open_camera)
add_subdirectory(point_cloud_from_file)
add_subdirectory(ptp)
add_subdirectory(threshold_from_file)
add_subdirectory(undistortion_from_file)
add_subdirectory(workspace_calibration_from_file)
add_subdirectory(system_timestamp)
add_subdirectory(textured_point_cloud_from_file)
